SELECT TF.NAME, TPM.NAME, TZM.NAME
FROM T_NEUZULASSUNGEN NZ
LEFT JOIN T_FAHRZEUGE TF ON nz.FAHRZEUGEN = tf.CODE
LEFT JOIN T_PKW_MARKEN TPM on tpm.CODE = nz.PKW_MARKEN
LEFT JOIN T_ZEIT_MONATSWERTE TZM on tzm.CODE = nz.ZEIT_MONATSWERTEN
where TPM.NAME LIKE 'Nilsson (S) <086495>';

SELECT TZM.NAME, sum(NEUZULASSUNGEN), LAG (sum(neuzulassungen)) over (partition by SUBSTR(TZM.NAME, 0, INSTR(TZM.NAME, ' ')-1) order by tzm.name)
FROM T_NEUZULASSUNGEN NZ
LEFT JOIN T_FAHRZEUGE TF ON nz.FAHRZEUGEN = tf.CODE
LEFT JOIN T_PKW_MARKEN TPM on tpm.CODE = nz.PKW_MARKEN
LEFT JOIN T_ZEIT_MONATSWERTE TZM on tzm.CODE = nz.ZEIT_MONATSWERTEN
where tzm.name is not null
GROUP BY TZM.NAME;